Repository saveourtool/diktat, pull requests merged in 2020-10, with the labels that each got.

#341 Rule 5.1.1
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/FunctionLengthWarnTest.kt
  info/available-rules.md
Labels: enhancement

#296 Recommendation 4.3.1 avoid nullable types
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/NullableTypeRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/NullableTypeRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/nullable/CollectionExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/nullable/CollectionTest.kt
  diktat-rules/src/test/resources/test/paragraph3/nullable/NullPrimitiveExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/nullable/NullPrimitiveTest.kt
  info/available-rules.md
Labels: enhancement

#359 Rule 5.2.2 parameters size
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionArgumentsSize.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/FunctionArgumentsSizeWarnTest.kt
  info/available-rules.md
Labels: enhancement

#360 Rule 5.2.1 lambda parameters order
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LambdaParameterOrder.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/LambdaParameterOrderWarnTest.kt
  info/available-rules.md
Labels: enhancement

#375 bugfix/suppress-bug(#372)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/SuppressTest.kt
Labels: bug

#346 Wrong newlines in functional style
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
Labels: bug

#361 Rule 5.1.3 avoid nested functions
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/AvoidNestedFunctionsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/AvoidNestedFunctionsWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph5/nested_functions/AvoidNestedFunctionsExample.kt
  diktat-rules/src/test/resources/test/paragraph5/nested_functions/AvoidNestedFunctionsNoTriggerExample.kt
  diktat-rules/src/test/resources/test/paragraph5/nested_functions/AvoidNestedFunctionsNoTriggerTest.kt
  diktat-rules/src/test/resources/test/paragraph5/nested_functions/AvoidNestedFunctionsSeveralExample.kt
  diktat-rules/src/test/resources/test/paragraph5/nested_functions/AvoidNestedFunctionsSeveralTest.kt
  diktat-rules/src/test/resources/test/paragraph5/nested_functions/AvoidNestedFunctionsTest.kt
  info/available-rules.md
Labels: enhancement

#348 Rule 5.1.2: Avoid deep nesting of function code blocks
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/NestedFunctionBlockWarnTest.kt
  info/available-rules.md
Labels: enhancement

#352 Improving variable search mechanism
  diktat-rules/pom.xml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImmutableValNoVarRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileSize.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/VariableSearchASTUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/search/VariablesSearch.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/search/VariablesWithAssignmentSearch.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/search/VariablesWithUsagesSearch.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/NoVarRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/VariablesSearchTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/VariablesWithAssignmentsSearchTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/VariablesWithUsagesSearchTest.kt
  pom.xml
Labels: enhancement

#370 Rule 5.2.3 Use default values for function arguments instead of overloading them
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/OverloadingArgumentsFunction.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/OverloadingArgumentsFunctionWarnTest.kt
  info/available-rules.md
Labels: enhancement

#332 Suggest using @property tag in KDoc
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KDocUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example2Expected.kt
  info/available-rules.md
Labels: enhancement

#392 Wildcard without "import" word
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt
Labels: bug

#381 create White Paper
  wp/logo.png
  wp/sections/introduction.tex
  wp/wp.tex
Labels: documentation

#388 feature/table-of-contents
  wp/wp.tex
Labels: documentation, enhancement

#394 Remove deprecated calculateLineColByOffset methods from Ktlint
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/PositionInTextLocator.kt
Labels: bug

#433 Rule 6.1.2. Prefer data classes instead of classes without any functional logic
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/DataClassesRuleWarnTest.kt
  info/available-rules.md
Labels: enhancement

#434 Rule 6.1.9
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PropertyAccessorFields.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/PropertyAccessorFieldsWarnTest.kt
  info/available-rules.md
Labels: enhancement

#311 Recommendation 4.2.1 smart casts
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SmartCastRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/SmartCastRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/SmartCastRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph4/smart_cast/SmartCastExpected.kt
  diktat-rules/src/test/resources/test/paragraph4/smart_cast/SmartCastTest.kt
  info/available-rules.md
Labels: enhancement

#457 Rule 6.1.6 abstract classes should have at least one abstract method
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/AbstractClassesFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/AbstractClassesWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph6/abstract_classes/ShouldRemoveAbstractKeywordExpected.kt
  diktat-rules/src/test/resources/test/paragraph6/abstract_classes/ShouldRemoveAbstractKeywordTest.kt
  info/available-rules.md
Labels: enhancement

#427 String template curly braces bugfix
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/StringTemplateRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/StringTemplateRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/string_template/StringTemplateExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/string_template/StringTemplateTest.kt
Labels: bug

#461 BlockStructureBraces assertion failed
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Test.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example3Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example3Test.kt
Labels: bug
