Repository saveourtool/diktat, pull requests merged in 2020-09, with the labels that each got.

#211 Feature/rule 3.3 lambdas when no braces
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement

#220 Fix KdocMethods
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/org/cqfn/diktat/kdoc/methods/KdocMethodsFullExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/org/cqfn/diktat/kdoc/methods/MissingKdocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/org/cqfn/diktat/kdoc/methods/MissingKdocWithModifiersExpected.kt
Labels: bug

#221 False-positive activation of 1TBS rule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/DoWhileBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/IfElseBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/LoopsBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/WhenBranchesExpected.kt
Labels: bug

#226 Sort Rule
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/SortRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/SortRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/sort_error/ConstantsExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/sort_error/ConstantsTest.kt
  diktat-rules/src/test/resources/test/paragraph3/sort_error/EnumSortExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/sort_error/EnumSortTest.kt
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement

#202 Recommendation-3.11-annotation-new-line
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AnnotationNewLineRule.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/AnnotationNewLineRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/AnnotationNewLineRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationConstructorSingleLineExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationConstructorSingleLineTest.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationSingleLineExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationSingleLineTest.kt
  info/available-rules.md
Labels: enhancement

#177 Recommendation-3.5-line-length-fix
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongExpressionNoFixExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongExpressionNoFixTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineCommentTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineExpressionExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineExpressionTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineFunExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineFunTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineRValueExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineRValueTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongShortRValueExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_line/LongShortRValueTest.kt
Labels: enhancement

#227 Recommendation 3.13 long numerical values separated
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LongNumericalValuesSeparatedRule.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LongNumericalValuesSeparatedFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LongNumericalValuesSeparatedWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/long_numbers/LongNumericalValuesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/long_numbers/LongNumericalValuesTest.kt
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement

#200 Feature/rule 3.10 when statement
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhenMustHaveElseRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/WhenMustHaveElseFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/WhenMustHaveElseWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/else_expected/ElseInWhenExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/else_expected/ElseInWhenTest.kt
  info/available-rules.md
Labels: enhancement

#231 Recommendation 3.12 multiple modifiers sequence
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/MultipleModifiersSequence.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/MultipleModifiersSequenceFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/MultipleModifiersSequenceWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/multiple_modifiers/ModifierExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/multiple_modifiers/ModifierTest.kt
  info/available-rules.md
Labels: enhancement

#237 KDocMethods arguments present
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocParamPresentWarnTest.kt
Labels: enhancement

#232 Changed maven deploy configuration
  .github/workflows/release.yml
  diktat-rules/pom.xml
  diktat-ruleset/pom.xml
  pom.xml
Labels: infrastructure

#222 Release automation - update versions and create pull request after new version is released
  .github/workflows/release.yml
Labels: infrastructure

#253 kdoc-reports-eol-error
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocFormatting.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingTest.kt
Labels: bug

#263 Annotations should be before modifiers
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/MultipleModifiersSequence.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/MultipleModifiersSequenceFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/MultipleModifiersSequenceWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/multiple_modifiers/AnnotationExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/multiple_modifiers/AnnotationTest.kt
Labels: enhancement

#252 Top level options in json configuration
  diktat-analysis.yml
  diktat-common/pom.xml
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/config/rules/RulesConfigReader.kt
  diktat-common/src/test/kotlin/org/cqfn/diktat/test/ConfigReaderTest.kt
  diktat-common/src/test/resources/test-rules-config.yml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PackageNaming.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackagePathFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigJsonTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
  pom.xml
Labels: enhancement

#246 Rule-1.2-confusing-identifier-naming
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  info/available-rules.md
Labels: enhancement

#265 Changing readme to prepare to release to central
  README.md
Labels: documentation

#256 Moving to maven central
  .github/workflows/diktat.yml
  .github/workflows/metrics_for_master.yml
  .github/workflows/release.yml
  README.md
  build.gradle.kts
  pom.xml
Labels: infrastructure

#269 False trigger at underscores in identifier naming rule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
Labels: bug

#272 Fixes to GPG handling in release workflow
  .github/workflows/release.yml
Labels: infrastructure

#273 Chapter 4 of Kotlin codestyle
  info/diktat-kotlin-coding-style-guide-en.md
Labels: documentation

#271 Documentation on symbols in test classes
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/config/rules/RulesConfigReader.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PackageNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/FunctonASTNodeUtils.kt
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
Labels: bug

#255 Suppress in individual files
  README.md
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AnnotationNewLineRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BracesInConditionalsAndLoopsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/EmptyBlock.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/EnumsSeparated.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FileNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LongNumericalValuesSeparatedRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/MultipleModifiersSequence.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PackageNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SingleLineStatementsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringConcatenationRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhenMustHaveElseRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/CommentsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/BlankLinesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileSize.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/IndentationRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocFormatting.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/SuppressTest.kt
Labels: enhancement

#308 Chapter 5 introduced
  info/diktat-kotlin-coding-style-guide-en.md
Labels: documentation

#270 Check if copyright year is valid
  diktat-rules/pom.xml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/WarningsGeneration.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/CopyrightDifferentYearExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/CopyrightDifferentYearTest.kt
  info/available-rules.md
  pom.xml
Labels: enhancement

#281 WildCards Import add documentation
  diktat-rules/src/main/resources/diktat-analysis.yml
  info/available-rules.md
Labels: documentation

#307 Update RulesConfigYamlTest
  diktat-analysis.yml
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigJsonTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigYamlTest.kt
Labels: tests

#287 Cover cases missing in recommendation 3.7
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/AnnotationExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/AnnotationTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/EqualsExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/EqualsTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/LbraceExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/LbraceTest.kt
Labels: enhancement

#319 Type alias wrong trigger
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/TypeAliasRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/TypeAliasRuleWarnTest.kt
Labels: bug

#305 Rule 3.14.2 string template format
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/StringTemplateRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/StringTemplateRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/string_template/StringTemplateExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/string_template/StringTemplateTest.kt
  info/available-rules.md
Labels: enhancement

#303 Rule 4.1.1 float arithmetic
  README.md
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/calculations/AccurateCalculationsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/PsiUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/AccurateCalculationsWarnTest.kt
  info/available-rules.md
Labels: enhancement

#235 Rule 2.6 follow ups
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/CommentsFormatting.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocFormatting.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/CommentsFormattingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/CommentsFormattingTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocCodeBlockFormattingExampleExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocCodeBlockFormattingExampleTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocCodeBlocksFormattingExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocCodeBlocksFormattingTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocEmptyLineExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocEmptyLineTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/KdocFormattingFullTest.kt
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement

#314 Recommendation 4.3.2 generic types explicit declaration
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/VariableGenericTypeDeclarationRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/VariableGenericTypeDeclarationRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/VariableGenericTypeDeclarationRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph4/generics/VariableGenericTypeDeclarationExpected.kt
  diktat-rules/src/test/resources/test/paragraph4/generics/VariableGenericTypeDeclarationTest.kt
  info/available-rules.md
Labels: enhancement

#340 Header missing for single object
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
Labels: bug

#345 Fixes bug in functional_tests.yml
  .github/workflows/functional_tests.yml
  pom.xml
Labels: bug

#328 Rule 4.1.3 Try to use 'val' instead of 'var' for variable declaration
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImmutableValNoVarRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/PsiUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/VariableSearchASTUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/NoVarRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/TypeAliasRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/VariableSearchASTUtilsTest.kt
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement
