Repository saveourtool/diktat, pull requests merged in 2020-07, with the labels that each got.

#17 Adding detekt static check action
  .github/workflows/detekt.yml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FileSize.kt
Labels: enhancement

#22 Adding badges and dev tools
  README.md
Labels: enhancement

#29 Nested blocks changed
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FileSize.kt
Labels: bug

#32 Changing readme, adding plugin for making a fat-jar
  CONTRIBUTING.md
  README.md
  diktat-common/pom.xml
  diktat-rules/pom.xml
  diktat-test-framework/pom.xml
  pom.xml
Labels: enhancement

#34 Changing readme, more info about maven run
  README.md
  diktat_small.jpg
Labels: documentation

#35 Release configuration using github actions
  .github/workflows/release.yml
  diktat-common/pom.xml
  diktat-rules/pom.xml
  diktat-test-framework/pom.xml
  pom.xml
Labels: enhancement

#36 Changing readme.md
  README.md
  diktat_small.jpg
  info/CHANGELOG.md
  info/CODE_OF_CONDUCT.md
  info/CONTRIBUTING.md
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: documentation

#46 Table with available checks, tests and fixmes
  .github/codecov.yml
  info/available-rules.md
Labels: documentation

#6 Added new check HEADER_NOT_BEFORE_PACKAGE
  .github/workflows/build_and_test.yml
  diktat-rules/pom.xml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/FixTestBase.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocAppendedCopyrightExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocAppendedCopyrightTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocNoCopyrightExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocNoCopyrightTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocTest.kt
Labels: enhancement

#10 Feature/rule 3.2
  diktat-rules/rules-config.json
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTestFix.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/BlankLinesBetweenBlocksExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/CopyrightCommentPositionExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/CopyrightCommentPositionTest.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/FileAnnotationExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/FileAnnotationTest.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/MissingBlankLinesBetweenBlocksTest.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/RedundantBlankLinesBetweenBlocksTest.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/ReorderingImportsExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/ReorderingImportsTest.kt
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement

#61 Rule 3.3
  diktat-rules/rules-config.json
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BracesInConditionalsAndLoopsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileSize.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocFormatting.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BracesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BracesRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileSizeWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/TestUtils.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/DoWhileBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/DoWhileBracesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/IfElseBraces1Expected.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/IfElseBraces1Test.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/LoopsBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/LoopsBracesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/WhenBranchesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/braces/WhenBranchesTest.kt
  info/available-rules.md
Labels: enhancement

#67 Add tests for AstNodeUtils class
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
Labels: tests

#78 Fixing issues with rules config when it caused an exception (closes #77)
  .github/workflows/diktat.yml
  README.md
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/config/reader/JsonResourceConfigReader.kt
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/config/rules/RulesConfigReader.kt
  diktat-common/src/main/resources/log4j.properties
  diktat-common/src/test/kotlin/org/cqfn/diktat/test/JsonReaderTest.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/resources/log4j.properties
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/DiktatRuleSetProviderTest.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/TestEntry.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/config/TestArgumentsReader.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/config/TestConfigReader.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/processing/TestProcessingFactory.kt
  diktat-test-framework/src/main/resources/log4j.properties
  info/diktat-kotlin-coding-style-guide-en.md
  pom.xml
Labels: bug

#97 Fixing issues found in #44 (identifier namings)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringCaseUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/MethodNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackagePathFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BracesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BracesRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ClassLikeStructuresOrderFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ClassLikeStructuresOrderRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileSizeWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTestFix.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/StringCaseUtilsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/FixTestBase.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/ConstantValNameExpected.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/ConstantValNameTest.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/PrefixInNameExpected.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/VarNameTest.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/VariableNamingExpected.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/VariableNamingTest.kt
  info/diktat-kotlin-coding-style-guide-en.md
Labels: bug

#100 Fixing issues found in #70 (companion object checks)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  info/diktat-kotlin-coding-style-guide-en.md
Labels: bug

#99 Rule 3.4 Block braces structure - correct errors
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/DoWhileBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/DoWhileBracesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/IfElseBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/IfElseBracesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/LoopsBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/LoopsBracesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/TryBraceExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/TryBraceTest.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/WhenBranchesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/WhenBranchesTest.kt
Labels: bug

#101 Tests to EnumValueCase
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/EnumValueCaseTest.kt
Labels: tests

#107 Hotfix: fixing issue when lambda arguments causes NPE on Identifier Naming rule (closing #106)
  README.md
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PackageNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/LambdaArgExpected.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/LambdaArgTest.kt
Labels: bug

#116 Updating code style and README
  README.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: enhancement

#113 Recommendation for 3.4: empty block
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/EmptyBlock.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/empty_block/TryCatchEmptyBlockExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/empty_block/TryCatchEmptyBlockTest.kt
  info/available-rules.md
Labels: enhancement

#126 Adding exception case for identifiers in catch block
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  info/diktat-kotlin-coding-style-guide-en.md
Labels: bug

#133 Removing ids from Warnings
  README.md
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
Labels: enhancement

#128 Recommendation for 3.4: statement per line
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SingleLineStatementsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/SequenceUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/SingleLineStatementsRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/SingleLineStatementsRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/statement/StatementExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/statement/StatementTest.kt
Labels: enhancement
