Repository saveourtool/diktat, pull requests merged in 2020-08, with the labels that each got.

#136 Recommendation-3.4-config
  diktat-rules/src/main/resources/rules-config.json
  info/available-rules.md
Labels: documentation

#142 Added check of `canBeAutoCorrected` field in tests
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/MethodNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt
Labels: enhancement, tests

#140 Refactoring of applyToCode method in TestUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/ASTNodeUtilsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/FunctionASTNodeUtilsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt
Labels: enhancement

#144 Do not force documentation on standard methods in MISSING_KDOC_CLASS_ELEMENTS
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/ASTConstants.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/FunctonASTNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
Labels: bug

#189 Feature/test tagging
  diktat-rules/pom.xml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/WarningsGeneration.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/EnumValueCaseTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/MethodNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackagePathFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocFormattingTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BracesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BracesRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ClassLikeStructuresOrderFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ClassLikeStructuresOrderRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileSizeWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTestFix.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/IndentationRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/IndentationRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/SingleLineStatementsRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/SingleLineStatementsRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/StringConcatenationWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/BlankLinesFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/BlankLinesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt
  pom.xml
Labels: tests

#198 NPE inside `ASTNodeUtils.findLBrace`
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/ASTConstants.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/empty_block/EmptyBlockExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/empty_block/EmptyBlockTest.kt
  diktat-rules/src/test/resources/test/paragraph3/empty_block/TryCatchEmptyBlockExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/empty_block/TryCatchEmptyBlockTest.kt
Labels: bug

#187 Recommendation-3.8-no-spaces
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/WarningsGeneration.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ConsecutiveSpacesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ConsecutiveSpacesRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/TooManySpacesEnumExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/TooManySpacesEnumTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/TooManySpacesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/TooManySpacesTest.kt
  info/available-rules.md
Labels: enhancement

#193 Adding tests to check that documentation and rules-config is correct
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/AvailableRulesDocTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigJsonTest.kt
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
  pom.xml
Labels: enhancement

#197 Recommendation 3.9 split enum
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/EnumsSeparated.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/rules-config.json
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EnumsSeparatedFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EnumsSeparatedWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/enum_separated/EnumSeparatedExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/enum_separated/EnumSeparatedTest.kt
  info/available-rules.md
Labels: enhancement

#188 Generate AST from code
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParseException.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParserTest.kt
Labels: enhancement

#212 bugfix/diktat-version-update
  README.md
  build.gradle.kts
  diktat-common/pom.xml
  diktat-rules/pom.xml
  diktat-test-framework/pom.xml
  pom.xml
Labels: bug

#213 Changing code style chapters numeration
  info/available-rules.md
  info/diktat-kotlin-coding-style-guide-en.md
Labels: documentation
