Repository saveourtool/diktat, pull requests merged in 2020-11, with the labels that each got.

#497 Confusing warning message in KDOC_NO_CONSTRUCTOR_PROPERTY
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
  info/available-rules.md
Labels: bug

#499 Recommendation 6.1.10 no tivial getters or setters are allowed
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/TrivialPropertyAccessors.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/TrivialPropertyAccessorsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/TrivialPropertyAccessorsWarnTest.kt
  diktat-rules/src/test/resources/test/chapter6/properties/TrivialPropertyAccessorsExpected.kt
  diktat-rules/src/test/resources/test/chapter6/properties/TrivialPropertyAccessorsTest.kt
  info/available-rules.md
Labels: enhancement

#509 Bugfix. Do not check KDoc on method main
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocWarnTest.kt
Labels: bug

#507 Bugfix. KDoc @return tag is suggested for extension functions which return Unit
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/org/cqfn/diktat/kdoc/methods/ReturnTagInsertionExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/org/cqfn/diktat/kdoc/methods/ReturnTagInsertionTested.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example1Expected.kt
Labels: bug

#512 Bugfix. NPE in TrivialPropertyAccessors rule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/TrivialPropertyAccessors.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/TrivialPropertyAccessorsFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/TrivialPropertyAccessorsWarnTest.kt
  diktat-rules/src/test/resources/test/chapter6/properties/TrivialPropertyAccessorsExpected.kt
  diktat-rules/src/test/resources/test/chapter6/properties/TrivialPropertyAccessorsTest.kt
Labels: bug

#458 Rule 6.1.5: Explicit supertype qualification should not be used if there is not clash between called methods
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/UselessSupertype.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/UselessSupertypeFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/UselessSupertypeWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph6/useless-override/SeveralSuperTypesExpected.kt
  diktat-rules/src/test/resources/test/paragraph6/useless-override/SeveralSuperTypesTest.kt
  diktat-rules/src/test/resources/test/paragraph6/useless-override/UselessOverrideExpected.kt
  diktat-rules/src/test/resources/test/paragraph6/useless-override/UselessOverrideTest.kt
  info/available-rules.md
Labels: enhancement

#500 NPE is ASTNode.squeezeSpaces method
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/CommentsFormatting.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/CommentsFormattingTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example3Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example3Test.kt
Labels: bug

#501 Rule 6.2.2(#447)
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ExtensionFunctionsSameNameRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ExtensionFunctionsSameNameWarnTest.kt
  info/available-rules.md
Labels: enhancement

#502 NPE in BlockStructureBraces
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example3Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example3Test.kt
Labels: bug

#513 Bugfix. Unhandled ArrayStoreException when string template has [] operator inside
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/StringTemplateRuleWarnTest.kt
Labels: bug

#536 Change generic-type algorithm
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
Labels: bug

#537 Bugfix. Newline at the beginning of code block is not removed if there are more than one
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/BlankLinesRule.kt
  diktat-rules/src/test/resources/test/paragraph3/blank_lines/CodeBlockWithBlankLinesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/blank_lines/CodeBlockWithBlankLinesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/blank_lines/RedundantBlankLinesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/blank_lines/RedundantBlankLinesTest.kt
Labels: bug

#549 WhiteSpaceRule after NewlinesRule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example2Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example2Test.kt
Labels: bug

#557 Function is not being simplified to expression body when semicolon is present
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/ASTConstants.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleFixTest.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/OneLineFunctionExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/OneLineFunctionTest.kt
Labels: bug

#535 Bugfix. False-positive LOCAL_VARIABLE_EARLY_DECLARATION
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Test.kt
Labels: bug

#465 Rule 6.1.7 implicit backing property(#443)
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ImplicitBackingPropertyWarnTest.kt
  info/available-rules.md
Labels: enhancement

#438 White-paper
  wp/pictures/class.PNG
  wp/pictures/data_flow.PNG
  wp/pictures/detekt.png
  wp/pictures/diktat.png
  wp/pictures/kotlinRating.png
  wp/pictures/ktfmt.png
  wp/pictures/ktlint.png
  wp/pictures/logo.png
  wp/pictures/sequence.jpg
  wp/pictures/web-example.png
  wp/references.bib
  wp/sections/appendix.tex
  wp/sections/chapter 4/cli.tex
  wp/sections/chapter 4/gradle.tex
  wp/sections/chapter 4/maven.tex
  wp/sections/chapter 4/rulesetConfiguration.tex
  wp/sections/compare.tex
  wp/sections/conclusion.tex
  wp/sections/definition.tex
  wp/sections/diKTat.tex
  wp/sections/download.tex
  wp/sections/examples.tex
  wp/sections/feature.tex
  wp/sections/introduction.tex
  wp/sections/kotlin.tex
  wp/sections/work.tex
  wp/wp.tex
Labels: documentation

#565 Bugfix. Make KDocs on overriden functions/properties false by default
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/FunctonASTNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt
Labels: bug

#540 Wrong braces with comments
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/CommentsFormatting.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/ASTConstants.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/IfElseBracesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/block_brace/IfElseBracesTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example2Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example2Test.kt
Labels: bug

#575 Private property in KDoc
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocTest.kt
Labels: bug

#566 Bugfix. Comments should be indented as the code they are commenting
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Test.kt
Labels: bug

#594 Bugfix. KdocMethod should not raise warning on override fun
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsTest.kt
Labels: bug
