Repository saveourtool/diktat, pull requests merged in 2020-12, with the labels that each got.

#545 Bugfix. Lambda passed as an argument is forced to be on the same line as the previous argument
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example1Test.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Test.kt
Labels: bug

#596 Bugfix. NPE in indentation rule(#555)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt
  diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt
  diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentTest.kt
Labels: bug

#508 Rule 6.4.1: Avoid using utility classes/objects
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidUtilityClass.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/AvoidUtilityClassWarnTest.kt
  info/available-rules.md
Labels: enhancement

#583 No trigger on individual tag without KDoc
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocMethodsTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocParamPresentWarnTest.kt
Labels: enhancement

#580 function style bug in NewlinesRule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LongNumericalValuesSeparatedRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/FunctionAstNodeUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/search/VariablesSearch.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/search/VariablesWithAssignmentSearch.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/search/VariablesWithUsagesSearch.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example1Expected.kt
Labels: bug

#598 KDoc check property in class
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt
  info/available-rules.md
Labels: enhancement

#600 Bugfix. CompactInitializationRule builds incorrect tree(#599)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Test.kt
Labels: bug

#620 Bugfix. FP EMPTY_BLOCK_STRUCTURE_ERROR on SAM overrides
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/EmptyBlock.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt
Labels: bug

#608 Feature. Recommendation 6.4.2: Objects should be used for Stateless Interfaces
  diktat-analysis.yml
  diktat-gradle-plugin/gradlew.bat
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/StatelessClassesRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/StatelessClassesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/StatelessClassesRuleWarnTest.kt
  diktat-rules/src/test/resources/test/chapter6/stateless_classes/StatelessClassExpected.kt
  diktat-rules/src/test/resources/test/chapter6/stateless_classes/StatelessClassTest.kt
  info/available-rules.md
Labels: enhancement

#635 Bugfix. FP of LOCAL_VARIABLE_EARLY_DECLARATION with other variables and a loop
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ExtensionFunctionsSameNameRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SmartCastRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt
Labels: bug

#634 Null safety in NewlinesRule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleTest.kt
Labels: bug

#637 Correct order in ClassLikeStructursOrderRule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ClassLikeStructuresOrderFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ClassLikeStructuresOrderRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/DeclarationsInClassOrderExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/OrderWithCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/file_structure/OrderWithCommentTest.kt
Labels: bug

#629 FP in AnnotationNewLineRule with comment
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AnnotationNewLineRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/AnnotationNewLineRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/AnnotationNewLineRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationCommentTest.kt
Labels: bug

#568 White-paper table generator
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/GenerationAvailableRules.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/LatexUtils.kt
  info/available-rules.md
  info/rules-mapping.md
  wp/pictures/package.png
  wp/pictures/sequence.PNG
  wp/pictures/sequence.jpg
  wp/pictures/useCase.png
  wp/sections/appendix.tex
  wp/sections/feature.tex
  wp/wp.tex
Labels: documentation, enhancement

#641 Whitepaper Update
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/GenerationDocs.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/LatexUtils.kt
  info/guide/diktat-coding-convention.md
  wp/sections/appendix.tex
Labels: documentation

#642 Bugfix. A lot of FP LOCAL_VARIABLE_EARLY_DECLARATION
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/GenerationDocs.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/LintTestBase.kt
Labels: bug

#650 Bugfix. Newline rule rbrace(#617)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt
Labels: bug

#646 Fix for incorrect variable name handle
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/VariableNamingExpected.kt
  diktat-rules/src/test/resources/test/paragraph1/naming/identifiers/VariableNamingTest.kt
Labels: enhancement

#648 Bugfix. Fix documentation generation(#647)
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/FullDocGenerator.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/LatexUtils.kt
  info/guide/diktat-coding-convention.md
  wp/sections/appendix.tex
Labels: bug, documentation

#661 Bugfix. Broken autofix for top-level block comment with multiline text
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/AutoCopyrightExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocAppendedCopyrightExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MisplacedHeaderKdocTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MultilineCopyrightExample.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MultilineCopyrightNotTriggerExample.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MultilineCopyrightNotTriggerTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/MultilineCopyrightTest.kt
  diktat-rules/src/test/resources/test/paragraph2/header/NewlineAfterHeaderKdocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/header/NewlineAfterHeaderKdocTest.kt
Labels: bug

#664 Bugfix. CommentedCode when text inside block comment may be interpreted as KDoc
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/CommentsRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Test.kt
Labels: bug

#662 Added fix in AnnotationNewLineRule
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AnnotationNewLineRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/AnnotationNewLineRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/annotations/AnnotationCommentTest.kt
Labels: bug

#665 Added links into appendix
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/LatexUtils.kt
  info/guide/diktat-coding-convention.md
  info/guide/guide-chapter-4.md
  info/guide/guide-chapter-5.md
  wp/sections/appendix.tex
Labels: documentation, enhancement

#670 Bugfix. When changing indentation of multiline string, all lines should be changed
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/IndentationRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example6Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example6Test.kt
Labels: bug

#671 DataClassesRule shouldn't trigger when no property in constructor
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/DataClassesRuleWarnTest.kt
Labels: bug

#675 Available-rules corrected according to diktat-coding-convention
  info/available-rules.md
Labels: bug, documentation

#673 Feature. All rules should be commented in diktat-analysis.yml
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ConsecutiveSpacesRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ConsecutiveSpacesRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigYamlTest.kt
Labels: enhancement

#681 Feature. Auto-fixes for null-checks
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullChecksRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/NullChecksRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter4/NullChecksRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/paragraph4/null_checks/IfConditionNullCheckExpected.kt
  diktat-rules/src/test/resources/test/paragraph4/null_checks/IfConditionNullCheckTest.kt
  diktat-rules/src/test/resources/test/paragraph4/null_checks/RequireFunctionExpected.kt
  diktat-rules/src/test/resources/test/paragraph4/null_checks/RequireFunctionTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example7Expected.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example7Test.kt
Labels: enhancement

#677 Feature. Allow more prefixes for boolean methods (#417)
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PackageNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
Labels: enhancement
