Repository saveourtool/diktat, pull requests merged in 2021-01, with the labels that each got.

#701 Bugfix. bug-documentation-generation
  info/buildSrc/gradle.properties
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/LatexUtils.kt
  wp/sections/appendix.tex
Labels: bug

#704 Do not use !isEmpty methods from the collections – need to use isNotEmpty instead
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/CheckInverseMethodRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/CheckInverseMethodRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/CheckInverseMethodRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph5/method_call_names/ReplaceMethodCallNamesExpected.kt
  diktat-rules/src/test/resources/test/paragraph5/method_call_names/ReplaceMethodCallNamesTest.kt
  info/available-rules.md
  info/guide/diktat-coding-convention.md
  info/guide/guide-TOC.md
  info/guide/guide-chapter-5.md
Labels: enhancement

#655 Final version of white-paper
  README.md
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt
  info/guide/diktat-coding-convention.md
  info/guide/guide-TOC.md
  info/guide/guide-chapter-2.md
  info/rules-mapping.md
  wp/README.md
  wp/makefile
  wp/references.bib
  wp/sections/appendix.tex
  wp/sections/compare.tex
  wp/sections/conclusion.tex
  wp/sections/definition.tex
  wp/sections/diKTat.tex
  wp/sections/download.tex
  wp/sections/examples.tex
  wp/sections/feature.tex
  wp/sections/introduction.tex
  wp/sections/kotlin.tex
  wp/sections/work.tex
  wp/wp.pdf
  wp/wp.tex
Labels: documentation

#680 New rule for complex expression
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AnnotationNewLineRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SmartCastRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
  info/available-rules.md
  info/guide/guide-chapter-3.md
Labels: enhancement

#708 Bugfix. Indentation-functions-expression-body(#683)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullChecksRule.kt
Labels: bug

#707 AsyncAndSyncRule
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AsyncAndSyncRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/AsyncAndSyncRuleTest.kt
  info/available-rules.md
  info/guide/guide-chapter-5.md
Labels: enhancement

#696 Warning for domain name
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/config/rules/RulesConfigReader.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/PackageNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt
Labels: enhancement

#715 Custom label
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BracesInConditionalsAndLoopsRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/CustomLabel.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstConstants.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/CustomLabelsTest.kt
  info/available-rules.md
  info/guide/guide-TOC.md
  info/guide/guide-chapter-5.md
Labels: enhancement

#712 Bugfix. Spaces are not inserted after { and before } in lambda expressions (#711)
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AsyncAndSyncRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/CheckInverseMethodRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LambdaLengthRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LambdaParameterOrder.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/OverloadingArgumentsFunction.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/TypeAliasRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/UselessSupertype.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/CommentsFormatting.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocComments.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/BracesLambdaSpacesExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/BracesLambdaSpacesTest.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/LambdaAsArgumentExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/spaces/LambdaAsArgumentTest.kt
Labels: bug

#724 Feature. Enable confiuring of ktlint reporter in gradle plugin
  README.md
  diktat-gradle-plugin/build.gradle.kts
  diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/DiktatGradlePluginFunctionalTest.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatExtension.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatGradlePlugin.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskBase.kt
  diktat-gradle-plugin/src/test/kotlin/org/cqfn/diktat/plugin/gradle/DiktatGradlePluginTest.kt
  diktat-gradle-plugin/src/test/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskTest.kt
Labels: plugins

#716 Add warning to suggest to use inline classes when a class has single property
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/InlineClassesRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/InlineClassesWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigYamlTest.kt
  info/available-rules.md
  info/guide/guide-TOC.md
  info/guide/guide-chapter-6.md
Labels: enhancement

#718 Disable chapters
  diktat-analysis.yml
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/config/rules/RulesConfigReader.kt
  diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/DiktatGradlePluginMultiprojectFunctionalTest.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Chapters.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example1-2Expected.kt
  info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/WarningsTableGenerator.kt
  info/guide/diktat-coding-convention.md
  info/guide/guide-chapter-5.md
  info/rules-mapping.md
  wp/sections/appendix.tex
Labels: enhancement

#733 A rule to check that there are no extension functions in the same file with the class(#731)
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/generated/WarningNames.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/ExtensionFunctionsInFileRule.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ExtensionFunctionsInFileWarnTest.kt
  info/available-rules.md
  info/guide/guide-TOC.md
  info/guide/guide-chapter-6.md
Labels: enhancement
