Repository saveourtool/diktat, pull requests merged in 2022-06, with the labels that each got.

#1363 Add unit tests for mis-indented expression body functions
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestMixin.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/FixTestBase.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/LintTestBase.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/processing/FileComparator.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/processing/FileComparisonResult.kt
  diktat-test-framework/src/main/kotlin/org/cqfn/diktat/test/framework/processing/TestComparatorUnit.kt
Labels: tests

#1370 Report unit test results via GitHub Actions
  .github/workflows/build_and_test.yml
Labels: infrastructure

#1371 Add unit tests which reproduce #1347
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestMixin.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt
Labels: tests

#1384 Bugfix/corrected readme
  info/README.md
  info/guide/diktat-coding-convention.md
  info/guide/guide-chapter-3.md
Labels: documentation

#1395 [#1330] Add more integration tests for `extendedIndentAfterOperators` flag
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestMixin.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt
Labels: tests

#1354 Bugfix: Checking white space before opening brace that starts a line
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/WhiteSpaceRule.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt
Labels: js
