Repository saveourtool/diktat, pull requests merged in 2022-07, with the labels that each got.

#1427 Get rid of the collapsible blocks in the CLI usage section
  README.md
Labels: documentation

#1431 Update guide-TOC.md
  info/guide/guide-TOC.md
Labels: documentation

#1433 Add unit tests for indentation in `if`- and `while`-expression predicates
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestResources.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt
Labels: tests

#1440 Update the version in `examples/maven/pom.xml` after the release
  .github/workflows/release.yml
  examples/maven/pom.xml
Labels: github_actions

#1441 Don't reformat indent-style comments
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/CommentsFormatting.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/CommentsFormattingFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/CommentsFormattingTest.kt
Labels: enhancement

#1432 Update guide-chapter-1.md
  info/guide/guide-chapter-1.md
Labels: documentation

#1443 Add an `extendedIndentForExpressionBodies` flag to the `WRONG_INDENTATION` check
  diktat-analysis.yml
  diktat-common/src/test/resources/test-rules-config.yml
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/IndentationConfig.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleFixTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestMixin.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestResources.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
  examples/gradle-groovy-dsl/diktat-analysis.yml
  examples/gradle-kotlin-dsl-multiproject/diktat-analysis.yml
  examples/gradle-kotlin-dsl/diktat-analysis.yml
  examples/maven/diktat-analysis.yml
  info/available-rules.md
  wp/sections/appendix.tex
Labels: enhancement

#1446 Add `gradle-kotlin-dsl-multiproject` to the list of example projects
  .github/workflows/release.yml
Labels: infrastructure

#1449 Add the default value of `extendedIndentBeforeDot` to `diktat-analysis.yml`
  diktat-rules/src/main/resources/diktat-analysis.yml
Labels: infrastructure

#1467 Correct the rule description
  info/available-rules.md
Labels: documentation

#1470 Refactor and clean up `IndentationRule`
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationAmount.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationAware.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationConfigAware.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/CustomIndentationChecker.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationConfigAwareTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestMixin.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
Labels: refactoring

#1473 Rewrite `getParenthesisIndentationChange()` to return `IndentationAmount`
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentedElementType.kt
Labels: refactoring

#1477 Add the retry logic and diagnostics to `DiktatSaveSmokeTest`
  diktat-rules/pom.xml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSaveSmokeTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTestBase.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt
Labels: tests, refactoring

#1479 Fix the missing fat JAR problem during the release procedure
  .github/workflows/release.yml
Labels: infrastructure

#1480 Improve `JAVA_HOME` comparison for forked tests
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSaveSmokeTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt
Labels: tests

#1481 Remove the circular dependency between `diktat-rules` and `diktat-ruleset`
  .github/workflows/build_and_test.yml
  .github/workflows/metrics_for_master.yml
  .github/workflows/release.yml
  .gitignore
  diktat-rules/pom.xml
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSaveSmokeTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/FixTestBase.kt
Labels: tests, infrastructure

#1482 Simplify Maven configuration by running `DiktatSaveSmokeTest` as an integration test
  diktat-rules/pom.xml
  pom.xml
Labels: tests, infrastructure
