Repository saveourtool/diktat, pull requests merged in 2023-12, with the labels that each got.

#1851 Fixed bug related to assigning to declared vals inside null-check branches
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter4/NullChecksRuleWarnTest.kt
Labels: bug

#1858 Fixed `WRONG_NEWLINES` rule to take into account `maxCallsInOneLine`
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
Labels: bug

#1864 Extracted `REDUNDANT_SEMICOLON` rule check from `WRONG_NEWLINES` rule
  diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/SemicolonsExpected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/SemicolonsTest.kt
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/DiktatRuleSetFactoryImpl.kt
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/SemicolonsRule.kt
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/identifiers/LocalVariablesRule.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/files/NewlinesRuleFixTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/files/SemicolonsRuleFixTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/files/SemicolonsRuleWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/OneLineFunctionExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/OneLineFunctionTest.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/SizeParameterListExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/newlines/SizeParameterListTest.kt
  diktat-rules/src/test/resources/test/paragraph3/semicolons/SemicolonsExpected.kt
  diktat-rules/src/test/resources/test/paragraph3/semicolons/SemicolonsTest.kt
Labels: bug, enhancement

#1873 Fixed duplicate `@property` generation for parameter with ' in name
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentPropertiesExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentPropertiesTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentTest.kt
Labels: bug

#1839 Updated README.md for Diktat 2.0
  .gitignore
  README.md
  diktat-cli/src/test/resources/test/smoke/build.gradle.kts_
  diktat-gradle-plugin/README.md
  diktat-gradle-plugin/src/functionalTest/kotlin/com/saveourtool/diktat/plugin/gradle/Utils.kt
  diktat-maven-plugin/README.md
Labels: documentation
