Repository saveourtool/diktat, pull requests merged in 2023-03, with the labels that each got.

#1633 Upgrade `com.github.gantsign.maven.plugin-tools:kotlin-maven-plugin-tools`
  diktat-maven-plugin/pom.xml
Labels: dependencies

#1634 Limit the maximum Maven Plug-in API version to be at most 3.6.4
  pom.xml
  renovate.json
Labels: dependencies

#1648 Wrap KtLint classes
  diktat-maven-plugin/src/main/kotlin/org/cqfn/diktat/plugin/maven/DiktatBaseMojo.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ktlint/KtLintRuleSetProviderWrapper.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ktlint/KtLintRuleSetWrapper.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ktlint/KtLintRuleWrapper.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRule.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSet.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProviderSpi.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/OrderedRuleSet.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/RunInScript.kt
  diktat-rules/src/main/resources/META-INF/services/com.pinterest.ktlint.core.RuleSetProvider
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ktlint/KtLintRuleSetWrapperTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/junit/IndentationTestWarnExtension.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/RulesConfigValidationTest.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/FixTestBase.kt
  diktat-rules/src/test/kotlin/org/cqfn/diktat/util/LintTestBase.kt
  diktat-ruleset/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt
Labels: refactoring

#1649 Diktat command
  .github/workflows/diktat_snapshot.yml
  build.gradle.kts
  diktat-common/src/main/kotlin/org/cqfn/diktat/common/ktlint/KtLintUtils.kt
  diktat-gradle-plugin/build.gradle.kts
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatGradlePlugin.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskBase.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/tasks/DiktatCheckTask.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/tasks/DiktatFixTask.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/tasks/DiktatTaskBase.kt
  diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/tasks/SarifReportMergeTask.kt
  diktat-gradle-plugin/src/test/kotlin/org/cqfn/diktat/plugin/gradle/DiktatGradlePluginTest.kt
  diktat-gradle-plugin/src/test/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskTest.kt
  diktat-gradle-plugin/src/test/kotlin/org/cqfn/diktat/plugin/gradle/ReporterSelectionTest.kt
  diktat-maven-plugin/build.gradle.kts
  diktat-maven-plugin/src/main/kotlin/org/cqfn/diktat/plugin/maven/DiktatBaseMojo.kt
  diktat-maven-plugin/src/main/kotlin/org/cqfn/diktat/plugin/maven/DiktatMojo.kt
  diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt
  diktat-ruleset/build.gradle.kts
  diktat-runner/diktat-runner-api/build.gradle.kts
  diktat-runner/diktat-runner-api/src/main/kotlin/org/cqfn/diktat/AbstractDiktatProcessCommand.kt
  diktat-runner/diktat-runner-api/src/main/kotlin/org/cqfn/diktat/DiktatProcessor.kt
  diktat-runner/diktat-runner-api/src/main/kotlin/org/cqfn/diktat/api/DiktatCallback.kt
  diktat-runner/diktat-runner-api/src/main/kotlin/org/cqfn/diktat/api/DiktatError.kt
  diktat-runner/diktat-runner-api/src/main/kotlin/org/cqfn/diktat/api/DiktatLogLevel.kt
  diktat-runner/diktat-runner-ktlint-engine/build.gradle.kts
  diktat-runner/diktat-runner-ktlint-engine/src/main/kotlin/org/cqfn/diktat/DiktatProcessCommand.kt
  diktat-runner/diktat-runner-ktlint-engine/src/main/kotlin/org/cqfn/diktat/ktlint/LintErrorCallbackWrapper.kt
  diktat-runner/diktat-runner-ktlint-engine/src/main/kotlin/org/cqfn/diktat/ktlint/LintErrorReporter.kt
  diktat-runner/diktat-runner-ktlint-engine/src/main/kotlin/org/cqfn/diktat/ktlint/LintErrorWrapper.kt
  gradle/plugins/src/main/kotlin/org/cqfn/diktat/buildutils/PublishingConfiguration.kt
  gradle/plugins/src/main/kotlin/org/cqfn/diktat/buildutils/diktat-convention-configuration.gradle.kts
  settings.gradle.kts
Labels: plugins, refactoring
