Repository saveourtool/diktat, pull requests merged in 2023-11, with the labels that each got.

#1767 Fixed warning `FUNCTION_BOOLEAN_PREFIX` on `operator fun`
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt
Labels: bug

#1780 Enhance tests in diktat
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/spaces/IndentationRuleFixTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/spaces/junit/IndentationTestFixExtension.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtilsTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/utils/KotlinParserTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/utils/VariablesWithAssignmentsSearchTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/utils/VariablesWithUsagesSearchTest.kt
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/util/FixTestBase.kt
  diktat-ruleset/src/test/kotlin/com/saveourtool/diktat/ruleset/smoke/DiktatSaveSmokeTest.kt
Labels: tests

#1782 Migrated smoke test to diktat cli
  diktat-cli/build.gradle.kts
  diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSaveSmokeTest.kt
  diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTest.kt
  diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt
  diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestUtils.kt
  diktat-cli/src/test/resources/test/smoke/.editorconfig
  diktat-cli/src/test/resources/test/smoke/.gitignore
  diktat-cli/src/test/resources/test/smoke/build.gradle.kts_
  diktat-cli/src/test/resources/test/smoke/save.toml
  diktat-cli/src/test/resources/test/smoke/src/jsMain/kotlin/com/saveourtool/diktat/scripts/ScriptExpected.kt
  diktat-cli/src/test/resources/test/smoke/src/jsMain/kotlin/com/saveourtool/diktat/scripts/ScriptTest.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Bug1Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/DefaultPackageExpected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/DefaultPackageTest.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example1-2Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example1Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example1Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example2Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example2Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example3Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example3Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example4Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example5Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example6Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example6Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example7Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example7Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/Example8Test.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/KdocFormattingMultilineTagsExpected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/KdocFormattingMultilineTagsTest.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/LocalVariableWithOffsetExpected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/LocalVariableWithOffsetTest.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/ManyLineTransformInLongLineExpected.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/ManyLineTransformInLongLineTest.kt
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/kotlin-library-expected.gradle.kts
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/kotlin-library.gradle.kts
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/save.toml
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/script/PackageInScriptExpected.kts
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/script/PackageInScriptTest.kts
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/script/SimpleRunInScriptExpected.kts
  diktat-cli/src/test/resources/test/smoke/src/main/kotlin/script/SimpleRunInScriptTest.kts
  diktat-ruleset/build.gradle.kts
Labels: tests

#1832 Fixed `KdocComments` for types in generic classes
  diktat-analysis.yml
  diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt
  diktat-rules/src/main/resources/diktat-analysis-huawei.yml
  diktat-rules/src/main/resources/diktat-analysis.yml
  diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNoKDocTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentPropertiesExpected.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentPropertiesTest.kt
  diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentTest.kt
  examples/gradle-groovy-dsl/diktat-analysis.yml
  examples/gradle-kotlin-dsl-multiproject/diktat-analysis.yml
  examples/gradle-kotlin-dsl/diktat-analysis.yml
  examples/maven-multiproject/diktat-analysis.yml
  examples/maven/diktat-analysis.yml
  info/available-rules.md
Labels: bug, enhancement
